# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_belt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='user_created',
        ),
        migrations.AddField(
            model_name='destination',
            name='planner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='python_belt_app.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(),
        ),
    ]
